[package]
name = "procmand"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
nix = "0.30.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
yaml-rust = "0.4"
